image: python:3.8

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python some_app.py
  only:
    - main
    - master
